### ISSUE TITLE
SGR 4 sub-parameters are treated as normal parameters

### ISSUE THREAD

**Issue by mkotowski** [charmbracelet/sequin#26]
**Describe the bug**
Sub-parameters for an SGR sequence are treated as additional SGR parameters.

**Setup**
Replicated in standard Ubuntu 24.04 container with `sequin 0.1.1 amd64` installed.

**To Reproduce**

1. Execute `echo -e '\e[4:1mUnderlined text, but no bold\e[m\n\e[4;1mBold AND underlined\e[m'`
2. Compare real terminal emulator output with the `sequin` ouput:

```sh
$ echo -e '\e[4:1mUnderlined text, but no bold\e[m\n\e[4;1mBold AND underlined\e[m' | sequin
 CSI 4:1m: Underline (Single), Bold
Text Underlined text, but no bold
 CSI m: Reset style
Ctrl \n: Line feed
 CSI 4;1m: Underline, Bold
Text Bold AND underlined
 CSI m: Reset style
Ctrl \n: Line feed
```

**Source Code**
To fix the issue, `i` index in SGR handling code at https://github.com/charmbracelet/sequin/blob/main/sgr.go#L39 needs to be incremented after the `param.HasMore()` check.

At least one `.golden` file also contains this error and also needs to be adjusted.

**Expected behavior**
Sub-parameters are checked for only once.

Expected:

```sh
$ echo -e '\e[4:1mUnderlined text, but no bold\e[m\n\e[4;1mBold AND underlined\e[m' | ./sequin
 CSI 4:1m: Underline (Single)
Text Underlined text, but no bold
 CSI m: Reset style
Ctrl \n: Line feed
 CSI 4;1m: Underline, Bold
Text Bold AND underlined
 CSI m: Reset style
Ctrl \n: Line feed
```

**Screenshots**
![Screenshot_20241121_062107](https://github.com/user-attachments/assets/0e120b7c-0793-4296-8352-b5543f6c784f)

**Additional context**
- Sub-parameter `0` needs additional consideration as it has effect of disabling the underline effect, but is currently reported as just "Underline"

**Comment by mkotowski** [comment]
To see proposed changes: https://github.com/charmbracelet/sequin/compare/main...mkotowski:sequin:fix/sgr4subparam?expand=1

**Comment by aymanbagabas** [comment]
Thank you, @mkotowski, for reporting this. It will be fixed in the next release 🙂

**Comment by meowgorithm** [comment]
You're a beast @mkotowski. I'm very impressed.
