### ISSUE TITLE
Cannot install with nix

### ISSUE THREAD

**Issue by FelisNivalis** [charmbracelet/sequin#41]
**Describe the bug**
`error: attribute 'sequin' missing` for `nur.repos.charmbracelet.sequin`

Not listed on the [NUR](https://nur.nix-community.org/repos/charmbracelet/) website. It seems you didn't add the package to your NUR. :)

**Comment by caarlos0** [comment]
fixed in https://github.com/charmbracelet/nur/commit/5575fe0a6e268aac408d8d429323fb5f07d8ae2c
